categories:
  - sms
  - mms
  - whatsapp
  - rcs
  - number-lookup
  - verification
  - voice
  - video
  - tutorials
  - contributing-guidelines
  - release-notes
  - atlas-platform
  - sinch-classic-sms
  - voice-cloud

filters:
  hostedFiles:
    baseUrl: https://sinch.github.io/docs/
